const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=__dirname+'/..';
function worker(){const events={},cache=new Map(),deletions=[];let offline=false;
 const box={self:{registration:{scope:'https://game.test/endurance/'},location:new URL('https://game.test/endurance/sw.js'),addEventListener:(t,fn)=>events[t]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}},URL,Request,Response,Set,
 fetch:async req=>{if(offline)throw new Error('offline');return new Response('online',{status:200});},caches:{open:async()=>({addAll:async paths=>{for(const p of paths){assert.ok(fs.existsSync(root+'/'+p.replace(/^\.\//,'')),p);cache.set(new URL(p,'https://game.test/endurance/').href,new Response(p.endsWith('.html')?'THE GAME':'ASSET'));}},put:async(req,res)=>{cache.set(typeof req==='string'?new URL(req,'https://game.test/endurance/').href:req.url,res);},match:async req=>cache.get(typeof req==='string'?new URL(req,'https://game.test/endurance/').href:req.url)?.clone()}),keys:async()=>['unrelated-site','endurance-static-v0'],delete:async key=>{deletions.push(key);return true;}}};
 assert.ok(fs.existsSync(root+'/sw.js'),'service worker must exist');vm.runInNewContext(fs.readFileSync(root+'/sw.js','utf8'),box);return {events,deletions,setOffline:()=>offline=true};}
test('PWA install precaches only existing local files; activate preserves other caches',async()=>{const w=worker();let done;w.events.install({waitUntil:p=>done=p});await done;w.events.activate({waitUntil:p=>done=p});await done;assert.deepEqual(w.deletions,['endurance-static-v0']);});
test('PWA navigation falls back to cached game when offline',async()=>{const w=worker();let done;w.events.install({waitUntil:p=>done=p});await done;w.setOffline();let response;w.events.fetch({request:{url:'https://game.test/endurance/index.html',method:'GET',mode:'navigate'},respondWith:p=>response=p});assert.equal(await (await response).text(),'THE GAME');});
test('PWA never intercepts unrelated origins or non-GET requests',()=>{const w=worker();for(const request of [{url:'https://external.test/',method:'GET',mode:'navigate'},{url:'https://game.test/endurance/',method:'POST',mode:'navigate'}])w.events.fetch({request,respondWith:()=>assert.fail('Unrelated request intercepted')});});
